### PR TITLE
find modal element by getElementById

### PR DESCRIPTION
**Pull request by 1vank1n**
This fix resolved problem with Safari at iOS < 11 at least (#9 ).

### CODE REVIEW

**Comment by 1vank1n** [comment]
I will appreciate if you add patch tag version. Because jsdelivr.com will could update version of your package at cdn.

**Comment by steelydylan** [comment]
Thank you :)

**Comment by steelydylan** [comment]
I just published v2.2.1 for you :)

**Comment by 1vank1n** [comment]
Thank you very much. Your lib is awesome! Used in many projects )

**Comment by steelydylan** [comment]
Oh I'm glad to hear that!!
I made many other libs so far such as smartphoto.js
https://github.com/appleple/SmartPhoto
Please use them sometimes, If you like.
and I will really appreciate it if you give me some feedbacks of the libraries.

**Pull request merged**
